# Generated by Django 5.2.17 on 2026-08-31 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('system_prompt', models.TextField()),
                ('model', models.CharField(default='gpt-4o', max_length=64)),
                ('project_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('slack_webhook_url', models.CharField(blank=True, max_length=512, null=True)),
                ('github_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('github_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('github_token', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_config', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('attendees', models.TextField(blank=True, null=True)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('proposal_content', models.TextField(blank=True, null=True)),
                ('proposal_draft_options', models.TextField(blank=True, null=True)),
                ('req_spec_content', models.TextField(blank=True, null=True)),
                ('proposal_status', models.CharField(choices=[('DRAFT', '초안'), ('PENDING_REVIEW', '검토 요청중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='DRAFT', max_length=20)),
                ('proposal_reject_reason', models.TextField(blank=True, null=True)),
                ('req_spec_status', models.CharField(choices=[('DRAFT', '초안'), ('PENDING_REVIEW', '검토 요청중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='DRAFT', max_length=20)),
                ('req_spec_reject_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('content', models.TextField()),
                ('sources_json', models.TextField()),
                ('degraded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssigneeRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=64)),
                ('candidate_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_recommendations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
