# Generated by Django 5.2.17 on 2026-08-31 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BACKLOG', '대기'), ('PENDING_APPROVAL', '배분승인대기'), ('IN_PROGRESS', '진행 중'), ('DONE', '완료'), ('CANCELLED', '취소됨')], default='BACKLOG', max_length=24)),
                ('difficulty', models.CharField(choices=[('HIGH', '상'), ('MEDIUM', '중'), ('LOW', '하')], default='MEDIUM', max_length=16)),
                ('difficulty_reason', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('assignment_reason', models.TextField(blank=True, null=True)),
                ('git_status', models.CharField(choices=[('NONE', '미연동'), ('PENDING', '대기'), ('IN_REVIEW', 'PR리뷰중'), ('MERGED', '완료')], default='NONE', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('wbs_start', models.DateField(blank=True, null=True)),
                ('wbs_end', models.DateField(blank=True, null=True)),
                ('source_document_id', models.CharField(blank=True, max_length=64, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
