# Generated by Django 5.2.17 on 2026-08-31 02:22

import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('PM', 'PM'), ('EMPLOYEE', '직원')], default='EMPLOYEE', max_length=16)),
                ('must_change_password', models.BooleanField(default=True)),
                ('employee_no', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('job_title', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('LEAVE', '휴직'), ('RESIGNED', '퇴사'), ('LOCKED', '잠금')], default='ACTIVE', max_length=16)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('slack_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('github_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tech_stack', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('past_projects', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
