# Generated by Django 5.2.17 on 2026-08-30 14:42

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('system_prompt', models.TextField()),
                ('model', models.CharField(default='gpt-4o', max_length=64)),
                ('project_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'user'), ('ai', 'ai'), ('system', 'system')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('slack_webhook_url', models.CharField(blank=True, max_length=512, null=True)),
                ('github_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('github_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('github_token', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_config', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('PM', 'PM'), ('EMPLOYEE', '직원')], default='EMPLOYEE', max_length=16)),
                ('must_change_password', models.BooleanField(default=True)),
                ('employee_no', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('job_title', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('LEAVE', '휴직'), ('RESIGNED', '퇴사'), ('LOCKED', '잠금')], default='ACTIVE', max_length=16)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('slack_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('github_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tech_stack', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('past_projects', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='info', max_length=16)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssigneeRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=64)),
                ('candidate_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_recommendations', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('attendees', models.TextField(blank=True, null=True)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('proposal_content', models.TextField(blank=True, null=True)),
                ('proposal_draft_options', models.TextField(blank=True, null=True)),
                ('req_spec_content', models.TextField(blank=True, null=True)),
                ('proposal_status', models.CharField(choices=[('DRAFT', '초안'), ('PENDING_REVIEW', '검토 요청중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='DRAFT', max_length=20)),
                ('proposal_reject_reason', models.TextField(blank=True, null=True)),
                ('req_spec_status', models.CharField(choices=[('DRAFT', '초안'), ('PENDING_REVIEW', '검토 요청중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='DRAFT', max_length=20)),
                ('req_spec_reject_reason', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('content', models.TextField()),
                ('sources_json', models.TextField()),
                ('degraded', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BACKLOG', '대기'), ('PENDING_APPROVAL', '배분승인대기'), ('IN_PROGRESS', '진행 중'), ('DONE', '완료'), ('CANCELLED', '취소됨')], default='BACKLOG', max_length=24)),
                ('difficulty', models.CharField(choices=[('HIGH', '상'), ('MEDIUM', '중'), ('LOW', '하')], default='MEDIUM', max_length=16)),
                ('difficulty_reason', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('assignment_reason', models.TextField(blank=True, null=True)),
                ('git_status', models.CharField(choices=[('NONE', '미연동'), ('PENDING', '대기'), ('IN_REVIEW', 'PR리뷰중'), ('MERGED', '완료')], default='NONE', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('wbs_start', models.DateField(blank=True, null=True)),
                ('wbs_end', models.DateField(blank=True, null=True)),
                ('source_document_id', models.CharField(blank=True, max_length=64, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
